version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:18.10-curl

    steps:
      - checkout
      - run: sudo apt-get update
      - run: echo Y | sudo apt-get install libboost-thread-dev libboost-test-dev cmake build-essential

      - run: mkdir build && cd build/ && cmake .. && make

      - run:
          name: MQTT_ClientLib tests
          command: cd build/MQTT_Client && ctest
          
