version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty

    steps:
      - checkout
      - run: sudo apt-get update
      - run: echo Y | sudo apt-get install libboost-thread-dev libboost-test-dev cmake

      - run: mkdir build && cd build/ && cmake ./build && make

      - run:
          name: Subscriber_Tests
          command: echo 1 2 3 | ./build/Subscriber/Subscriber
      - run:
          name: Publisher_Tests
          command: echo 1 2 3 | ./build/Publisher/Publisher

      - run:
          name: Print the Current Time
          command: date
